name: kafka

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set environment variables based on branch
        run: |
          echo "HOST=${{ secrets.AWS_VM_HOST }}" >> $GITHUB_ENV

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_VM_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "$HOST" >> ~/.ssh/known_hosts

      - name: Deploy to AWS VM
        run: |
          ssh ${{ secrets.AWS_VM_USER }}@"$HOST" << 'EOF'
            cd ./sprintforge-kafka

            if [ ! -f .env ]; then
              echo "Creating .env file..."
              cat <<EOT > .env
KAFKA_PORT=9092
STATIC_IP=${HOST}
EOT
            fi

            git checkout ${GITHUB_REF_NAME}
            git pull

            sudo docker compose down
            sudo docker compose up -d
          EOF
