name: kafka

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set HOST env
        run: echo "HOST=${{ secrets.AWS_VM_HOST }}" >> $GITHUB_ENV

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_VM_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "$HOST" >> ~/.ssh/known_hosts

      - name: Deploy to AWS VM
        run: |
          ssh ${{ secrets.AWS_VM_USER }}@"$HOST" << EOF
            set -e

            cd ~

            if [ ! -d "sprintforge-kafka" ]; then
              git clone https://github.com/MarianoFrancisco/sprintforge-kafka.git
            fi

            cd sprintforge-kafka

            sudo docker network inspect kafka-network >/dev/null 2>&1 || sudo docker network create kafka-network

            if [ ! -f .env ]; then
              echo "KAFKA_PORT=9092" > .env
              echo "STATIC_IP=${HOST}" >> .env
            fi

            git fetch --all
            git checkout ${GITHUB_REF_NAME}
            git pull

            sudo docker compose down || true
            sudo docker compose up -d
          EOF
